### ISSUE TITLE
Shift+Enter doesn't work -- unable to get to the next line

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#11]
refact-vscode: v3.1.108 (pre-release)

It works, but inconsistently, sometimes it just sends instead of hopping on the next line

**Comment by valaises** [comment]
It works, but not always, so it's a bug

**Comment by MarcMcIntosh** [comment]
could be fixed here https://github.com/smallcloudai/refact-chat-js/pull/10/commits/4b479f9a3ca855d4699039f5a71eff01476430af

**Comment by valaises** [comment]
haven't reproduced after the fixes (yet) 😸
