### ISSUE TITLE
FIM debug page crashes

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#12]
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/60dbbb4f-aefb-49fd-8496-d2c3744f330a)

VSCode: Version: 1.87.2 (Universal)
Refact plugin: v3.1.108 (pre-release)

How to reproduce:
1. Open VSCode
2. Hit FIM
3. Open a file (I opened an empty one)
4. make some completion
5. see fim debug page crushed and you cannot interact with Refact anymore

**Comment by MarcMcIntosh** [comment]
Fixed here: https://github.com/smallcloudai/refact-chat-js/pull/10/commits/4dd984600c172ba14335fbfa9f972c734bca06df
