### ISSUE TITLE
Weird at-command completion behaviour

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#13]
v3.1.108 (pre-release)

https://github.com/smallcloudai/refact-chat-js/assets/43416739/8cd29bb5-3f4d-4b5e-a015-b3505dc7518a

**Comment by valaises** [comment]
duplicates in at-command completion output are already reported in https://github.com/smallcloudai/refact-lsp/issues/151

**Comment by MarcMcIntosh** [comment]
Yes, I was able to recreate the issue when duplicates where in the combobox.
Here's a quick fix https://github.com/smallcloudai/refact-chat-js/pull/10/commits/c0f7e4d2feee99f6afc6450d69e2a210ff88770b

**Comment by valaises** [comment]
There's still that weird behaviour

https://github.com/smallcloudai/refact-chat-js/assets/43416739/1b8b8f7f-8eec-49d0-9aa5-b81f9820b826
