### ISSUE TITLE
Retry should be blocked until stream is over / interrupted

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#14]
Refact v3.1.108 (pre-release)

https://github.com/smallcloudai/refact-chat-js/assets/43416739/be96c6e2-6ffd-4a08-80ce-822c83bb3e41

**Comment by valaises** [comment]
btw, I would hide retry for all messages other that last one

**Comment by valaises** [comment]
looks like I've uploaded the wrong video :D

**Comment by valaises** [comment]
The thing was that retry button should be disabled until stream is over. At the current version you are able to retry while the answer is streaming. This behavior causes a mess

**Comment by MarcMcIntosh** [comment]
yes, will I publish another alpha so you can test the fixes?

**Comment by valaises** [comment]
I'd be really happy if those changes were a part of a pre-release plugin

**Comment by MarcMcIntosh** [comment]
done :)

**Comment by valaises** [comment]
works 👍🏻
