### ISSUE TITLE
Render Mathematical Formulas 

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#15]
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/24b6e5f7-5591-443f-84cb-90e3427b26ea)

**Comment by valaises** [comment]
I think it's a latex

**Comment by MarcMcIntosh** [comment]
Looks posable: https://github.com/remarkjs/react-markdown/issues/10#issuecomment-347763068

**Comment by MarcMcIntosh** [comment]
It's been added here https://github.com/smallcloudai/refact-chat-js/pull/10/commits/04369575e6836dcca655015d7add5650a51c552f

By default the lsp doesn't respond with math blocks that can be parsed

the options I've tried are. in the storybook file,  inline math use `$` delimiters `$C_L$` and for blocks
`\n$$\n` or ```math\nC_F\n```

```
$$
x = \\frac{{-b \\pm \\sqrt{{b^2 - 4ac}}}}{{2a}}
$$
```

**Comment by valaises** [comment]
it works 👍🏻. Altho, we need to modify system prompt ain't we?

**Comment by MarcMcIntosh** [comment]
Yes, we'll need to modify the system prompt
