### ISSUE TITLE
Unable to Attach Selected Text if message is not the first one

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#16]
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/2874ab45-31e7-43a0-84cf-fb0fd0d27a38)

**Comment by MarcMcIntosh** [comment]
🤔 could be a useful feature, although the controls will take up some extra space

**Comment by valaises** [comment]
yeah, it's quite useful! Old chat had it
