### ISSUE TITLE
Issues with sync with enhance UX for @commands

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#21]
1. When completing paths, by default selected row is out of box
incorrect:
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/55e4608c-7eb6-4b01-9f28-e92062024627)
should be something like this:
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/618ef69e-4c55-40eb-bb16-abd203e2b016)
2. no support for completion for multiple commands in a single row
incorrect:
![image](https://github.com/smallcloudai/refact-chat-js/assets/43416739/3e22e0f8-7aaa-4fbe-a318-4c83c15670ad)

**Comment by valaises** [comment]
yep, sorry about the second. It's mine :)
fixed here: https://github.com/smallcloudai/refact-lsp/pull/170/commits/36bca7b4f20751ba8ae000c45440445d1f9c571e

**Comment by MarcMcIntosh** [comment]
Should be fixed here https://github.com/smallcloudai/refact-chat-js/pull/23
