### ISSUE TITLE
[Feature Request] Swap key binds for sending a message and getting to the new line

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#33]
I still have an issue when message gets accidentally sent when I'm getting to the new line and it kinda bothers me when I'm in a middle of a complex prompt

So, I propose to make an option in the settings to swap "Send message" (Enter) and Goto new line (Shift + Enter) => Send message (Shift + Enter), Goto new line (Enter)

**Comment by MarcMcIntosh** [comment]
#69
