### ISSUE TITLE
Bug with completion of @-commands

### ISSUE THREAD

**Issue by valaises** [smallcloudai/refact-chat-js#36]
https://github.com/smallcloudai/refact-chat-js/assets/43416739/baacad3b-60a6-49ea-b3af-e9e42ea0d830

**Comment by MarcMcIntosh** [comment]
Hmm, looks like the replace values not update due to the debounce.

**Comment by MarcMcIntosh** [comment]
Fixed here https://github.com/smallcloudai/refact-chat-js/pull/27/commits/42a21e66a771e39652a0174af8f2798a00080af1
